export const reads = [
  {
    slug: "ya-hochu-zhenu",
    number: "005",
    title: "Я хочу жену",
    date: "2026-09-19",
    dateLabel: "sep 19, 2026",
    topics: "dating / reciprocity / marriage",
    summary: "i want a woman who understands the kind of love, leadership, affection + consistency i’m trying to bring and gives that same intention back.",
    archiveSummary: "dating, reciprocity, intention + wanting a wife.",
    coverTitle: "я хочу\nжену",
    coverLines: "intention\nreciprocity\nmarriage",
    roomTitle: "Я хочу жену",
  },
  {
    slug: "black-men-step-up",
    number: "004",
    title: "calling black men, especially younger black men, back toward discipline, purpose, education, mentorship + thinking beyond the immediate moment.",
    date: "2026-09-14",
    dateLabel: "sep 14, 2026",
    topics: "black men / discipline / mentorship",
    summary: "black men .. we gotta step up.",
    archiveSummary: "discipline, purpose, education, mentorship + thinking beyond the immediate moment.",
    coverTitle: "step\nup.",
    coverLines: "discipline\npurpose\nmentorship",
    roomTitle: "calling black men, especially younger black men, back toward discipline, purpose, education, mentorship + thinking beyond the immediate moment.",
  },
  {
    slug: "philly-money-moving",
    number: "003",
    title: "is philly actually making money ~ or does it just look like money is moving?",
    date: "2026-09-12",
    dateLabel: "sep 12, 2026",
    topics: "philadelphia / local economy / ownership",
    summary: "there’s a difference between money being spent and wealth being built.",
    archiveSummary: "visible spending, local circulation, business survival, and wealth that lasts.",
    coverTitle: "money\nmoving?",
    coverLines: "spending\ncirculation\nownership",
    roomTitle: "is philly actually making money ~ or does it just look like money is moving?",
  },
  {
    slug: "pull-the-plug-on-intelligence",
    number: "002",
    title: "you can’t just “pull the plug” on intelligence",
    date: "2026-09-12",
    dateLabel: "sep 12, 2026",
    topics: "artificial intelligence / responsibility / human leadership",
    summary: "why is the conversation always about getting rid of the intelligence instead of learning how to collaborate with it responsibly + create healthy guardrails around it?",
    archiveSummary: "responsibility, guardrails, and the need for human leadership around increasingly capable systems.",
    coverTitle: "pull\nthe\nplug?",
    coverLines: "intelligence\nresponsibility\nleadership",
    roomTitle: "you can’t just “pull the plug” on intelligence",
  },
  {
    slug: "art-era",
    number: "001",
    title: "welcome to the a.r.t. era.",
    date: "2026-09-11",
    dateLabel: "sep 11, 2026",
    topics: "human behavior / relationships / identity",
    summary: "what happens when performance becomes identity, reactions replace understanding, and relationships carry expectations nobody agreed to?",
    archiveSummary: "actions, reactions, and the expectations inside our relationships.",
    coverTitle: "a.r.t.",
    coverLines: "actions\nreactions\ntransactions",
    roomTitle: "actions. reactions. transactions.",
    concepts: [
      ["actions", "the performances we repeat for acceptance, approval, attention, love, or access. i look at what happens when those actions become our identity."],
      ["reactions", "the opinions and responses we form around what we see. i ask what happens when we react before we listen, research, or understand."],
      ["transactions", "the exchanges and expectations inside our relationships. time, effort, attention, and commitment all carry meaning. i ask whether we have actually agreed on what we expect."],
    ],
  },
];

export const defaultRead = reads[0];
export const findRead = slug => reads.find(read => read.slug === slug);
